name = "Amble DSL"
grammar = "amble_dsl"
path_suffixes = ["amble"]
line_comments = ["# "]
scopes = ["source.amble"]
autoclose_before = ",)]}"
brackets = [
  { start = "{", end = "}", close = true, newline = true, not_in = ["comment", "string"] },
  { start = "(", end = ")", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "[", end = "]", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
]
# word_characters = ["A-Za-z0-9_", ":", "-", "#"]
