id = "amble_dsl"
name = "Amble DSL"
version = "0.1.0"
schema_version = 1
authors = ["David Brown <djvbmd@protonmail.com>"]
description = "DSL for game world creation for the Amble engine."

# Explicitly register the language definition
languages = ["languages/amble_dsl"]

[grammars.amble_dsl]
repository = "file:///home/dave/Code/rust/amble/tree-sitter-amble-script"
rev = "acf4b7a8de5a6787186004fe224394b97eeafebb"
