/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 125
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 94
#define ALIAS_COUNT 0
#define TOKEN_COUNT 50
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  sym_number = 3,
  aux_sym_string_token1 = 4,
  aux_sym_string_token2 = 5,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 6,
  aux_sym_string_token3 = 7,
  aux_sym_string_token4 = 8,
  aux_sym_string_token5 = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  anon_sym_let = 12,
  anon_sym_set = 13,
  anon_sym_EQ = 14,
  anon_sym_LPAREN = 15,
  anon_sym_COMMA = 16,
  anon_sym_RPAREN = 17,
  anon_sym_trigger = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_room = 21,
  anon_sym_name = 22,
  anon_sym_desc = 23,
  anon_sym_description = 24,
  anon_sym_visited = 25,
  anon_sym_exit = 26,
  anon_sym_DASH_GT = 27,
  anon_sym_item = 28,
  anon_sym_portable = 29,
  anon_sym_spinner = 30,
  anon_sym_wedge = 31,
  anon_sym_width = 32,
  anon_sym_npc = 33,
  anon_sym_location = 34,
  anon_sym_nowhere = 35,
  anon_sym_goal = 36,
  anon_sym_group = 37,
  anon_sym_required = 38,
  anon_sym_optional = 39,
  anon_sym_status_DASHeffect = 40,
  anon_sym_done = 41,
  anon_sym_when = 42,
  anon_sym_has = 43,
  anon_sym_flag = 44,
  anon_sym_missing = 45,
  anon_sym_reached = 46,
  anon_sym_complete = 47,
  anon_sym_in = 48,
  anon_sym_progress = 49,
  sym_program = 50,
  sym_string = 51,
  sym_boolean = 52,
  sym_set_decl = 53,
  sym_set_list = 54,
  sym_trigger = 55,
  sym__trigger_stmt = 56,
  sym_room_def = 57,
  sym_room_block = 58,
  sym_room_stmt = 59,
  sym_room_name = 60,
  sym_room_desc = 61,
  sym_room_visited = 62,
  sym_exit_stmt = 63,
  sym_item_def = 64,
  sym_item_block = 65,
  sym_item_stmt = 66,
  sym_item_name = 67,
  sym_item_desc = 68,
  sym_item_portable = 69,
  sym_spinner_def = 70,
  sym_spinner_block = 71,
  sym_wedge_stmt = 72,
  sym_npc_def = 73,
  sym_npc_block = 74,
  sym_npc_stmt = 75,
  sym_npc_name = 76,
  sym_npc_desc = 77,
  sym_npc_location = 78,
  sym_goal_def = 79,
  sym_goal_stmt = 80,
  sym_goal_desc = 81,
  sym_goal_group = 82,
  sym_goal_done = 83,
  sym_goal_cond = 84,
  aux_sym_program_repeat1 = 85,
  aux_sym_string_repeat1 = 86,
  aux_sym_set_list_repeat1 = 87,
  aux_sym_trigger_repeat1 = 88,
  aux_sym_room_block_repeat1 = 89,
  aux_sym_item_block_repeat1 = 90,
  aux_sym_spinner_block_repeat1 = 91,
  aux_sym_npc_block_repeat1 = 92,
  aux_sym_goal_def_repeat1 = 93,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [aux_sym_string_token3] = "string_token3",
  [aux_sym_string_token4] = "string_token4",
  [aux_sym_string_token5] = "string_token5",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_let] = "let",
  [anon_sym_set] = "set",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_trigger] = "trigger",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_room] = "room",
  [anon_sym_name] = "name",
  [anon_sym_desc] = "desc",
  [anon_sym_description] = "description",
  [anon_sym_visited] = "visited",
  [anon_sym_exit] = "exit",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_item] = "item",
  [anon_sym_portable] = "portable",
  [anon_sym_spinner] = "spinner",
  [anon_sym_wedge] = "wedge",
  [anon_sym_width] = "width",
  [anon_sym_npc] = "npc",
  [anon_sym_location] = "location",
  [anon_sym_nowhere] = "nowhere",
  [anon_sym_goal] = "goal",
  [anon_sym_group] = "group",
  [anon_sym_required] = "required",
  [anon_sym_optional] = "optional",
  [anon_sym_status_DASHeffect] = "status-effect",
  [anon_sym_done] = "done",
  [anon_sym_when] = "when",
  [anon_sym_has] = "has",
  [anon_sym_flag] = "flag",
  [anon_sym_missing] = "missing",
  [anon_sym_reached] = "reached",
  [anon_sym_complete] = "complete",
  [anon_sym_in] = "in",
  [anon_sym_progress] = "progress",
  [sym_program] = "program",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_set_decl] = "set_decl",
  [sym_set_list] = "set_list",
  [sym_trigger] = "trigger",
  [sym__trigger_stmt] = "_trigger_stmt",
  [sym_room_def] = "room_def",
  [sym_room_block] = "room_block",
  [sym_room_stmt] = "room_stmt",
  [sym_room_name] = "room_name",
  [sym_room_desc] = "room_desc",
  [sym_room_visited] = "room_visited",
  [sym_exit_stmt] = "exit_stmt",
  [sym_item_def] = "item_def",
  [sym_item_block] = "item_block",
  [sym_item_stmt] = "item_stmt",
  [sym_item_name] = "item_name",
  [sym_item_desc] = "item_desc",
  [sym_item_portable] = "item_portable",
  [sym_spinner_def] = "spinner_def",
  [sym_spinner_block] = "spinner_block",
  [sym_wedge_stmt] = "wedge_stmt",
  [sym_npc_def] = "npc_def",
  [sym_npc_block] = "npc_block",
  [sym_npc_stmt] = "npc_stmt",
  [sym_npc_name] = "npc_name",
  [sym_npc_desc] = "npc_desc",
  [sym_npc_location] = "npc_location",
  [sym_goal_def] = "goal_def",
  [sym_goal_stmt] = "goal_stmt",
  [sym_goal_desc] = "goal_desc",
  [sym_goal_group] = "goal_group",
  [sym_goal_done] = "goal_done",
  [sym_goal_cond] = "goal_cond",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_set_list_repeat1] = "set_list_repeat1",
  [aux_sym_trigger_repeat1] = "trigger_repeat1",
  [aux_sym_room_block_repeat1] = "room_block_repeat1",
  [aux_sym_item_block_repeat1] = "item_block_repeat1",
  [aux_sym_spinner_block_repeat1] = "spinner_block_repeat1",
  [aux_sym_npc_block_repeat1] = "npc_block_repeat1",
  [aux_sym_goal_def_repeat1] = "goal_def_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [aux_sym_string_token4] = aux_sym_string_token4,
  [aux_sym_string_token5] = aux_sym_string_token5,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_trigger] = anon_sym_trigger,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_room] = anon_sym_room,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_desc] = anon_sym_desc,
  [anon_sym_description] = anon_sym_description,
  [anon_sym_visited] = anon_sym_visited,
  [anon_sym_exit] = anon_sym_exit,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_item] = anon_sym_item,
  [anon_sym_portable] = anon_sym_portable,
  [anon_sym_spinner] = anon_sym_spinner,
  [anon_sym_wedge] = anon_sym_wedge,
  [anon_sym_width] = anon_sym_width,
  [anon_sym_npc] = anon_sym_npc,
  [anon_sym_location] = anon_sym_location,
  [anon_sym_nowhere] = anon_sym_nowhere,
  [anon_sym_goal] = anon_sym_goal,
  [anon_sym_group] = anon_sym_group,
  [anon_sym_required] = anon_sym_required,
  [anon_sym_optional] = anon_sym_optional,
  [anon_sym_status_DASHeffect] = anon_sym_status_DASHeffect,
  [anon_sym_done] = anon_sym_done,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_flag] = anon_sym_flag,
  [anon_sym_missing] = anon_sym_missing,
  [anon_sym_reached] = anon_sym_reached,
  [anon_sym_complete] = anon_sym_complete,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_progress] = anon_sym_progress,
  [sym_program] = sym_program,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_set_decl] = sym_set_decl,
  [sym_set_list] = sym_set_list,
  [sym_trigger] = sym_trigger,
  [sym__trigger_stmt] = sym__trigger_stmt,
  [sym_room_def] = sym_room_def,
  [sym_room_block] = sym_room_block,
  [sym_room_stmt] = sym_room_stmt,
  [sym_room_name] = sym_room_name,
  [sym_room_desc] = sym_room_desc,
  [sym_room_visited] = sym_room_visited,
  [sym_exit_stmt] = sym_exit_stmt,
  [sym_item_def] = sym_item_def,
  [sym_item_block] = sym_item_block,
  [sym_item_stmt] = sym_item_stmt,
  [sym_item_name] = sym_item_name,
  [sym_item_desc] = sym_item_desc,
  [sym_item_portable] = sym_item_portable,
  [sym_spinner_def] = sym_spinner_def,
  [sym_spinner_block] = sym_spinner_block,
  [sym_wedge_stmt] = sym_wedge_stmt,
  [sym_npc_def] = sym_npc_def,
  [sym_npc_block] = sym_npc_block,
  [sym_npc_stmt] = sym_npc_stmt,
  [sym_npc_name] = sym_npc_name,
  [sym_npc_desc] = sym_npc_desc,
  [sym_npc_location] = sym_npc_location,
  [sym_goal_def] = sym_goal_def,
  [sym_goal_stmt] = sym_goal_stmt,
  [sym_goal_desc] = sym_goal_desc,
  [sym_goal_group] = sym_goal_group,
  [sym_goal_done] = sym_goal_done,
  [sym_goal_cond] = sym_goal_cond,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_set_list_repeat1] = aux_sym_set_list_repeat1,
  [aux_sym_trigger_repeat1] = aux_sym_trigger_repeat1,
  [aux_sym_room_block_repeat1] = aux_sym_room_block_repeat1,
  [aux_sym_item_block_repeat1] = aux_sym_item_block_repeat1,
  [aux_sym_spinner_block_repeat1] = aux_sym_spinner_block_repeat1,
  [aux_sym_npc_block_repeat1] = aux_sym_npc_block_repeat1,
  [aux_sym_goal_def_repeat1] = aux_sym_goal_def_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trigger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_room] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_desc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_visited] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_item] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_portable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spinner] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_wedge] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_width] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_npc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_location] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nowhere] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_group] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_optional] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_status_DASHeffect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_done] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_missing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_reached] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_complete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_progress] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_set_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_set_list] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger] = {
    .visible = true,
    .named = true,
  },
  [sym__trigger_stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_room_def] = {
    .visible = true,
    .named = true,
  },
  [sym_room_block] = {
    .visible = true,
    .named = true,
  },
  [sym_room_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_room_name] = {
    .visible = true,
    .named = true,
  },
  [sym_room_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_room_visited] = {
    .visible = true,
    .named = true,
  },
  [sym_exit_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_item_def] = {
    .visible = true,
    .named = true,
  },
  [sym_item_block] = {
    .visible = true,
    .named = true,
  },
  [sym_item_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_item_name] = {
    .visible = true,
    .named = true,
  },
  [sym_item_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_item_portable] = {
    .visible = true,
    .named = true,
  },
  [sym_spinner_def] = {
    .visible = true,
    .named = true,
  },
  [sym_spinner_block] = {
    .visible = true,
    .named = true,
  },
  [sym_wedge_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_def] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_block] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_name] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_location] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_def] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_group] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_done] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_cond] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trigger_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_room_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_spinner_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_npc_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_goal_def_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 59,
  [61] = 56,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 2,
  [96] = 3,
  [97] = 4,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(145);
      ADVANCE_MAP(
        '"', 2,
        '#', 147,
        '\'', 6,
        '(', 164,
        ')', 166,
        ',', 165,
        '-', 8,
        '=', 163,
        '\\', 143,
        'c', 96,
        'd', 30,
        'e', 141,
        'f', 9,
        'g', 100,
        'h', 13,
        'i', 87,
        'l', 31,
        'm', 67,
        'n', 12,
        'o', 106,
        'p', 98,
        'r', 32,
        's', 45,
        't', 109,
        'v', 70,
        'w', 33,
        '{', 168,
        '}', 169,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '#') ADVANCE(146);
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '}') ADVANCE(169);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(151);
      if (lookahead == '\\') ADVANCE(144);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(150);
      if (lookahead == '\\') ADVANCE(144);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '#') ADVANCE(147);
      if (lookahead == '\\') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(157);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(152);
      if (lookahead == '\\') ADVANCE(142);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(42);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(80);
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(86);
      if (lookahead == 'o') ADVANCE(140);
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(116);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(78);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(79);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'q') ADVANCE(138);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(130);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(135);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(82);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(182);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(172);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(128);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 25:
      if (lookahead == 'd') ADVANCE(195);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(174);
      END_STATE();
    case 27:
      if (lookahead == 'd') ADVANCE(187);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(60);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(129);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(119);
      if (lookahead == 'o') ADVANCE(91);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'o') ADVANCE(101);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'h') ADVANCE(44);
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(190);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(171);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(159);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(160);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(180);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(184);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(196);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(178);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(126);
      if (lookahead == 'p') ADVANCE(66);
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(111);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(134);
      END_STATE();
    case 55:
      if (lookahead == 'f') ADVANCE(56);
      END_STATE();
    case 56:
      if (lookahead == 'f') ADVANCE(50);
      END_STATE();
    case 57:
      if (lookahead == 'g') ADVANCE(193);
      END_STATE();
    case 58:
      if (lookahead == 'g') ADVANCE(194);
      END_STATE();
    case 59:
      if (lookahead == 'g') ADVANCE(113);
      END_STATE();
    case 60:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 61:
      if (lookahead == 'g') ADVANCE(49);
      END_STATE();
    case 62:
      if (lookahead == 'g') ADVANCE(61);
      END_STATE();
    case 63:
      if (lookahead == 'h') ADVANCE(181);
      END_STATE();
    case 64:
      if (lookahead == 'h') ADVANCE(52);
      END_STATE();
    case 65:
      if (lookahead == 'h') ADVANCE(46);
      END_STATE();
    case 66:
      if (lookahead == 'i') ADVANCE(95);
      END_STATE();
    case 67:
      if (lookahead == 'i') ADVANCE(121);
      END_STATE();
    case 68:
      if (lookahead == 'i') ADVANCE(62);
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 69:
      if (lookahead == 'i') ADVANCE(102);
      END_STATE();
    case 70:
      if (lookahead == 'i') ADVANCE(124);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(92);
      END_STATE();
    case 72:
      if (lookahead == 'i') ADVANCE(127);
      END_STATE();
    case 73:
      if (lookahead == 'i') ADVANCE(133);
      END_STATE();
    case 74:
      if (lookahead == 'i') ADVANCE(103);
      END_STATE();
    case 75:
      if (lookahead == 'i') ADVANCE(115);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(104);
      END_STATE();
    case 77:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 78:
      if (lookahead == 'l') ADVANCE(185);
      END_STATE();
    case 79:
      if (lookahead == 'l') ADVANCE(188);
      END_STATE();
    case 80:
      if (lookahead == 'l') ADVANCE(122);
      END_STATE();
    case 81:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 82:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 83:
      if (lookahead == 'm') ADVANCE(177);
      END_STATE();
    case 84:
      if (lookahead == 'm') ADVANCE(170);
      END_STATE();
    case 85:
      if (lookahead == 'm') ADVANCE(107);
      END_STATE();
    case 86:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 87:
      if (lookahead == 'n') ADVANCE(197);
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 88:
      if (lookahead == 'n') ADVANCE(191);
      END_STATE();
    case 89:
      if (lookahead == 'n') ADVANCE(183);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(173);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 94:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 95:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 96:
      if (lookahead == 'o') ADVANCE(85);
      END_STATE();
    case 97:
      if (lookahead == 'o') ADVANCE(137);
      END_STATE();
    case 98:
      if (lookahead == 'o') ADVANCE(112);
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 99:
      if (lookahead == 'o') ADVANCE(59);
      END_STATE();
    case 100:
      if (lookahead == 'o') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(97);
      END_STATE();
    case 101:
      if (lookahead == 'o') ADVANCE(84);
      END_STATE();
    case 102:
      if (lookahead == 'o') ADVANCE(93);
      END_STATE();
    case 103:
      if (lookahead == 'o') ADVANCE(89);
      END_STATE();
    case 104:
      if (lookahead == 'o') ADVANCE(90);
      END_STATE();
    case 105:
      if (lookahead == 'p') ADVANCE(186);
      END_STATE();
    case 106:
      if (lookahead == 'p') ADVANCE(131);
      END_STATE();
    case 107:
      if (lookahead == 'p') ADVANCE(81);
      END_STATE();
    case 108:
      if (lookahead == 'p') ADVANCE(136);
      END_STATE();
    case 109:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 110:
      if (lookahead == 'r') ADVANCE(179);
      END_STATE();
    case 111:
      if (lookahead == 'r') ADVANCE(167);
      END_STATE();
    case 112:
      if (lookahead == 'r') ADVANCE(132);
      END_STATE();
    case 113:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 114:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 115:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 116:
      if (lookahead == 's') ADVANCE(192);
      END_STATE();
    case 117:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 118:
      if (lookahead == 's') ADVANCE(198);
      END_STATE();
    case 119:
      if (lookahead == 's') ADVANCE(21);
      END_STATE();
    case 120:
      if (lookahead == 's') ADVANCE(71);
      END_STATE();
    case 121:
      if (lookahead == 's') ADVANCE(120);
      END_STATE();
    case 122:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 123:
      if (lookahead == 's') ADVANCE(118);
      END_STATE();
    case 124:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 125:
      if (lookahead == 't') ADVANCE(161);
      END_STATE();
    case 126:
      if (lookahead == 't') ADVANCE(162);
      END_STATE();
    case 127:
      if (lookahead == 't') ADVANCE(175);
      END_STATE();
    case 128:
      if (lookahead == 't') ADVANCE(189);
      END_STATE();
    case 129:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 130:
      if (lookahead == 't') ADVANCE(139);
      END_STATE();
    case 131:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 132:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 133:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 134:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 135:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 136:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 137:
      if (lookahead == 'u') ADVANCE(105);
      END_STATE();
    case 138:
      if (lookahead == 'u') ADVANCE(75);
      END_STATE();
    case 139:
      if (lookahead == 'u') ADVANCE(117);
      END_STATE();
    case 140:
      if (lookahead == 'w') ADVANCE(64);
      END_STATE();
    case 141:
      if (lookahead == 'x') ADVANCE(72);
      END_STATE();
    case 142:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 143:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(158);
      END_STATE();
    case 144:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(147);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(153);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_string_token3);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '#') ADVANCE(147);
      if (lookahead == '\\') ADVANCE(156);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#') ADVANCE(154);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(158);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '"') ADVANCE(153);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_string_token5);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_trigger);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_room);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_desc);
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_visited);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_exit);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_item);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_portable);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_spinner);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_wedge);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_width);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_npc);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_location);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_nowhere);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_goal);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_group);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_required);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(anon_sym_optional);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_status_DASHeffect);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_done);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(anon_sym_flag);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_missing);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(anon_sym_reached);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_complete);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_progress);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 1},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [aux_sym_string_token4] = ACTIONS(1),
    [aux_sym_string_token5] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_trigger] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_room] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_desc] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_visited] = ACTIONS(1),
    [anon_sym_exit] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_item] = ACTIONS(1),
    [anon_sym_portable] = ACTIONS(1),
    [anon_sym_spinner] = ACTIONS(1),
    [anon_sym_wedge] = ACTIONS(1),
    [anon_sym_width] = ACTIONS(1),
    [anon_sym_npc] = ACTIONS(1),
    [anon_sym_location] = ACTIONS(1),
    [anon_sym_nowhere] = ACTIONS(1),
    [anon_sym_goal] = ACTIONS(1),
    [anon_sym_group] = ACTIONS(1),
    [anon_sym_required] = ACTIONS(1),
    [anon_sym_optional] = ACTIONS(1),
    [anon_sym_status_DASHeffect] = ACTIONS(1),
    [anon_sym_done] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_flag] = ACTIONS(1),
    [anon_sym_missing] = ACTIONS(1),
    [anon_sym_reached] = ACTIONS(1),
    [anon_sym_complete] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_progress] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(103),
    [sym_set_decl] = STATE(6),
    [sym_trigger] = STATE(6),
    [sym_room_def] = STATE(6),
    [sym_item_def] = STATE(6),
    [sym_spinner_def] = STATE(6),
    [sym_npc_def] = STATE(6),
    [sym_goal_def] = STATE(6),
    [aux_sym_program_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_trigger] = ACTIONS(9),
    [anon_sym_room] = ACTIONS(11),
    [anon_sym_item] = ACTIONS(13),
    [anon_sym_spinner] = ACTIONS(15),
    [anon_sym_npc] = ACTIONS(17),
    [anon_sym_goal] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_desc,
    ACTIONS(21), 19,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_RBRACE,
      anon_sym_room,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_item,
      anon_sym_portable,
      anon_sym_spinner,
      anon_sym_wedge,
      anon_sym_width,
      anon_sym_npc,
      anon_sym_location,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [28] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_desc,
    ACTIONS(25), 19,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_RBRACE,
      anon_sym_room,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_item,
      anon_sym_portable,
      anon_sym_spinner,
      anon_sym_wedge,
      anon_sym_width,
      anon_sym_npc,
      anon_sym_location,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [56] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_desc,
    ACTIONS(29), 19,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_RBRACE,
      anon_sym_room,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_item,
      anon_sym_portable,
      anon_sym_spinner,
      anon_sym_wedge,
      anon_sym_width,
      anon_sym_npc,
      anon_sym_location,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [84] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_let,
    ACTIONS(38), 1,
      anon_sym_trigger,
    ACTIONS(41), 1,
      anon_sym_room,
    ACTIONS(44), 1,
      anon_sym_item,
    ACTIONS(47), 1,
      anon_sym_spinner,
    ACTIONS(50), 1,
      anon_sym_npc,
    ACTIONS(53), 1,
      anon_sym_goal,
    STATE(5), 8,
      sym_set_decl,
      sym_trigger,
      sym_room_def,
      sym_item_def,
      sym_spinner_def,
      sym_npc_def,
      sym_goal_def,
      aux_sym_program_repeat1,
  [122] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_trigger,
    ACTIONS(11), 1,
      anon_sym_room,
    ACTIONS(13), 1,
      anon_sym_item,
    ACTIONS(15), 1,
      anon_sym_spinner,
    ACTIONS(17), 1,
      anon_sym_npc,
    ACTIONS(19), 1,
      anon_sym_goal,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(5), 8,
      sym_set_decl,
      sym_trigger,
      sym_room_def,
      sym_item_def,
      sym_spinner_def,
      sym_npc_def,
      sym_goal_def,
      aux_sym_program_repeat1,
  [160] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_desc,
    ACTIONS(62), 1,
      anon_sym_group,
    ACTIONS(64), 1,
      anon_sym_done,
    STATE(9), 2,
      sym_goal_stmt,
      aux_sym_goal_def_repeat1,
    STATE(13), 3,
      sym_goal_desc,
      sym_goal_group,
      sym_goal_done,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [192] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_desc,
    ACTIONS(71), 1,
      anon_sym_group,
    ACTIONS(74), 1,
      anon_sym_done,
    STATE(8), 2,
      sym_goal_stmt,
      aux_sym_goal_def_repeat1,
    STATE(13), 3,
      sym_goal_desc,
      sym_goal_group,
      sym_goal_done,
    ACTIONS(66), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [224] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_desc,
    ACTIONS(62), 1,
      anon_sym_group,
    ACTIONS(64), 1,
      anon_sym_done,
    STATE(8), 2,
      sym_goal_stmt,
      aux_sym_goal_def_repeat1,
    STATE(13), 3,
      sym_goal_desc,
      sym_goal_group,
      sym_goal_done,
    ACTIONS(77), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [256] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(81), 1,
      anon_sym_name,
    ACTIONS(83), 1,
      anon_sym_desc,
    ACTIONS(85), 1,
      anon_sym_description,
    ACTIONS(87), 1,
      anon_sym_visited,
    ACTIONS(89), 1,
      anon_sym_exit,
    STATE(11), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(43), 4,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_exit_stmt,
  [288] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_name,
    ACTIONS(83), 1,
      anon_sym_desc,
    ACTIONS(85), 1,
      anon_sym_description,
    ACTIONS(87), 1,
      anon_sym_visited,
    ACTIONS(89), 1,
      anon_sym_exit,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(12), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(43), 4,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_exit_stmt,
  [320] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_name,
    ACTIONS(98), 1,
      anon_sym_desc,
    ACTIONS(101), 1,
      anon_sym_description,
    ACTIONS(104), 1,
      anon_sym_visited,
    ACTIONS(107), 1,
      anon_sym_exit,
    STATE(12), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(43), 4,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_exit_stmt,
  [352] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [386] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [420] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 11,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_desc,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
      anon_sym_group,
      anon_sym_done,
  [454] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(124), 1,
      anon_sym_name,
    ACTIONS(126), 1,
      anon_sym_desc,
    ACTIONS(128), 1,
      anon_sym_description,
    ACTIONS(130), 1,
      anon_sym_portable,
    STATE(21), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
    STATE(50), 3,
      sym_item_name,
      sym_item_desc,
      sym_item_portable,
  [482] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 1,
      anon_sym_name,
    ACTIONS(136), 1,
      anon_sym_desc,
    ACTIONS(138), 1,
      anon_sym_description,
    ACTIONS(140), 1,
      anon_sym_location,
    STATE(22), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
    STATE(52), 3,
      sym_npc_name,
      sym_npc_desc,
      sym_npc_location,
  [510] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 1,
      anon_sym_name,
    ACTIONS(126), 1,
      anon_sym_desc,
    ACTIONS(128), 1,
      anon_sym_description,
    ACTIONS(130), 1,
      anon_sym_portable,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
    STATE(50), 3,
      sym_item_name,
      sym_item_desc,
      sym_item_portable,
  [538] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_name,
    ACTIONS(136), 1,
      anon_sym_desc,
    ACTIONS(138), 1,
      anon_sym_description,
    ACTIONS(140), 1,
      anon_sym_location,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(23), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
    STATE(52), 3,
      sym_npc_name,
      sym_npc_desc,
      sym_npc_location,
  [566] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    ACTIONS(148), 1,
      anon_sym_name,
    ACTIONS(151), 1,
      anon_sym_desc,
    ACTIONS(154), 1,
      anon_sym_description,
    ACTIONS(157), 1,
      anon_sym_location,
    STATE(23), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
    STATE(52), 3,
      sym_npc_name,
      sym_npc_desc,
      sym_npc_location,
  [594] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(162), 1,
      anon_sym_name,
    ACTIONS(165), 1,
      anon_sym_desc,
    ACTIONS(168), 1,
      anon_sym_description,
    ACTIONS(171), 1,
      anon_sym_portable,
    STATE(24), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
    STATE(50), 3,
      sym_item_name,
      sym_item_desc,
      sym_item_portable,
  [622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [636] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [678] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [692] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [706] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [720] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [734] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [748] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [762] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [776] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [790] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [804] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [818] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [832] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_trigger,
      anon_sym_room,
      anon_sym_item,
      anon_sym_spinner,
      anon_sym_npc,
      anon_sym_goal,
  [860] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_desc,
    ACTIONS(208), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_portable,
  [875] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_desc,
    ACTIONS(212), 5,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_desc,
    ACTIONS(216), 5,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
  [903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_desc,
    ACTIONS(220), 5,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
  [917] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_desc,
    ACTIONS(224), 5,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
  [931] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_goal,
    ACTIONS(230), 1,
      anon_sym_has,
    ACTIONS(232), 1,
      anon_sym_flag,
    ACTIONS(234), 1,
      anon_sym_missing,
    ACTIONS(236), 1,
      anon_sym_reached,
    STATE(17), 1,
      sym_goal_cond,
  [953] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_desc,
    ACTIONS(238), 5,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
  [967] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_desc,
    ACTIONS(242), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_portable,
  [980] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_desc,
    ACTIONS(246), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_portable,
  [993] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_desc,
    ACTIONS(250), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_portable,
  [1006] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_desc,
    ACTIONS(254), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_location,
  [1019] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_desc,
    ACTIONS(258), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_portable,
  [1032] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_desc,
    ACTIONS(262), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_location,
  [1045] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_desc,
    ACTIONS(266), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_location,
  [1058] = 4,
    ACTIONS(270), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
    ACTIONS(274), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [1073] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_desc,
    ACTIONS(276), 4,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_location,
  [1086] = 4,
    ACTIONS(270), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
    ACTIONS(282), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [1101] = 4,
    ACTIONS(270), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(56), 1,
      aux_sym_string_repeat1,
    ACTIONS(287), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [1116] = 4,
    ACTIONS(270), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(61), 1,
      aux_sym_string_repeat1,
    ACTIONS(291), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [1131] = 4,
    ACTIONS(270), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
    ACTIONS(274), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [1146] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
    ACTIONS(297), 1,
      anon_sym_wedge,
    STATE(70), 2,
      sym_wedge_stmt,
      aux_sym_spinner_block_repeat1,
  [1160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_identifier,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(76), 2,
      sym__trigger_stmt,
      aux_sym_trigger_repeat1,
  [1174] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(85), 1,
      sym_string,
  [1190] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(55), 1,
      sym_string,
  [1206] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(54), 1,
      sym_string,
  [1222] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(45), 1,
      sym_string,
  [1238] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym__trigger_stmt,
      aux_sym_trigger_repeat1,
  [1252] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(53), 1,
      sym_string,
  [1268] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
    ACTIONS(316), 1,
      anon_sym_wedge,
    STATE(70), 2,
      sym_wedge_stmt,
      aux_sym_spinner_block_repeat1,
  [1282] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(49), 1,
      sym_string,
  [1298] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(57), 1,
      sym_string,
  [1314] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(7), 1,
      sym_string,
  [1330] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      aux_sym_string_token1,
    ACTIONS(321), 1,
      aux_sym_string_token2,
    ACTIONS(323), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(90), 1,
      sym_string,
  [1346] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(15), 1,
      sym_string,
  [1362] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym_identifier,
    ACTIONS(325), 1,
      anon_sym_RBRACE,
    STATE(68), 2,
      sym__trigger_stmt,
      aux_sym_trigger_repeat1,
  [1376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_wedge,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_wedge_stmt,
      aux_sym_spinner_block_repeat1,
  [1390] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      aux_sym_string_token1,
    ACTIONS(305), 1,
      aux_sym_string_token2,
    ACTIONS(307), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(44), 1,
      sym_string,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_COMMA,
    ACTIONS(332), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_set_list_repeat1,
  [1419] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_set_list_repeat1,
  [1432] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 3,
      anon_sym_required,
      anon_sym_optional,
      anon_sym_status_DASHeffect,
  [1441] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(340), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_set_list_repeat1,
  [1454] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(51), 1,
      sym_boolean,
    ACTIONS(342), 2,
      anon_sym_true,
      anon_sym_false,
  [1465] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(46), 1,
      sym_boolean,
    ACTIONS(342), 2,
      anon_sym_true,
      anon_sym_false,
  [1476] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      anon_sym_width,
    ACTIONS(344), 2,
      anon_sym_RBRACE,
      anon_sym_wedge,
  [1487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_complete,
    ACTIONS(350), 1,
      anon_sym_in,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 2,
      anon_sym_item,
      anon_sym_flag,
  [1505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
    STATE(34), 1,
      sym_spinner_block,
  [1515] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_item_block,
  [1525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_identifier,
    ACTIONS(358), 1,
      anon_sym_RBRACE,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 2,
      anon_sym_RBRACE,
      anon_sym_wedge,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1551] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_npc_block,
  [1561] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      anon_sym_room,
    ACTIONS(366), 1,
      anon_sym_nowhere,
  [1571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      sym_identifier,
  [1581] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    ACTIONS(27), 1,
      sym_identifier,
  [1591] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      sym_identifier,
  [1601] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym_room_block,
  [1611] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_set_list,
  [1621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      sym_identifier,
  [1628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_complete,
  [1635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_EQ,
  [1642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      ts_builtin_sym_end,
  [1649] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_flag,
  [1656] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      anon_sym_room,
  [1663] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      anon_sym_set,
  [1670] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      sym_identifier,
  [1677] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_identifier,
  [1684] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
  [1691] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      anon_sym_LBRACE,
  [1698] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_identifier,
  [1705] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      anon_sym_DASH_GT,
  [1712] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      anon_sym_progress,
  [1719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      sym_identifier,
  [1726] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      sym_identifier,
  [1733] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      anon_sym_when,
  [1740] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_identifier,
  [1747] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(402), 1,
      sym_identifier,
  [1754] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(404), 1,
      sym_identifier,
  [1761] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(406), 1,
      sym_identifier,
  [1768] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(408), 1,
      sym_identifier,
  [1775] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(410), 1,
      sym_identifier,
  [1782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(412), 1,
      sym_number,
  [1789] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(414), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 192,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 352,
  [SMALL_STATE(14)] = 369,
  [SMALL_STATE(15)] = 386,
  [SMALL_STATE(16)] = 403,
  [SMALL_STATE(17)] = 420,
  [SMALL_STATE(18)] = 437,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 482,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 538,
  [SMALL_STATE(23)] = 566,
  [SMALL_STATE(24)] = 594,
  [SMALL_STATE(25)] = 622,
  [SMALL_STATE(26)] = 636,
  [SMALL_STATE(27)] = 650,
  [SMALL_STATE(28)] = 664,
  [SMALL_STATE(29)] = 678,
  [SMALL_STATE(30)] = 692,
  [SMALL_STATE(31)] = 706,
  [SMALL_STATE(32)] = 720,
  [SMALL_STATE(33)] = 734,
  [SMALL_STATE(34)] = 748,
  [SMALL_STATE(35)] = 762,
  [SMALL_STATE(36)] = 776,
  [SMALL_STATE(37)] = 790,
  [SMALL_STATE(38)] = 804,
  [SMALL_STATE(39)] = 818,
  [SMALL_STATE(40)] = 832,
  [SMALL_STATE(41)] = 846,
  [SMALL_STATE(42)] = 860,
  [SMALL_STATE(43)] = 875,
  [SMALL_STATE(44)] = 889,
  [SMALL_STATE(45)] = 903,
  [SMALL_STATE(46)] = 917,
  [SMALL_STATE(47)] = 931,
  [SMALL_STATE(48)] = 953,
  [SMALL_STATE(49)] = 967,
  [SMALL_STATE(50)] = 980,
  [SMALL_STATE(51)] = 993,
  [SMALL_STATE(52)] = 1006,
  [SMALL_STATE(53)] = 1019,
  [SMALL_STATE(54)] = 1032,
  [SMALL_STATE(55)] = 1045,
  [SMALL_STATE(56)] = 1058,
  [SMALL_STATE(57)] = 1073,
  [SMALL_STATE(58)] = 1086,
  [SMALL_STATE(59)] = 1101,
  [SMALL_STATE(60)] = 1116,
  [SMALL_STATE(61)] = 1131,
  [SMALL_STATE(62)] = 1146,
  [SMALL_STATE(63)] = 1160,
  [SMALL_STATE(64)] = 1174,
  [SMALL_STATE(65)] = 1190,
  [SMALL_STATE(66)] = 1206,
  [SMALL_STATE(67)] = 1222,
  [SMALL_STATE(68)] = 1238,
  [SMALL_STATE(69)] = 1252,
  [SMALL_STATE(70)] = 1268,
  [SMALL_STATE(71)] = 1282,
  [SMALL_STATE(72)] = 1298,
  [SMALL_STATE(73)] = 1314,
  [SMALL_STATE(74)] = 1330,
  [SMALL_STATE(75)] = 1346,
  [SMALL_STATE(76)] = 1362,
  [SMALL_STATE(77)] = 1376,
  [SMALL_STATE(78)] = 1390,
  [SMALL_STATE(79)] = 1406,
  [SMALL_STATE(80)] = 1419,
  [SMALL_STATE(81)] = 1432,
  [SMALL_STATE(82)] = 1441,
  [SMALL_STATE(83)] = 1454,
  [SMALL_STATE(84)] = 1465,
  [SMALL_STATE(85)] = 1476,
  [SMALL_STATE(86)] = 1487,
  [SMALL_STATE(87)] = 1497,
  [SMALL_STATE(88)] = 1505,
  [SMALL_STATE(89)] = 1515,
  [SMALL_STATE(90)] = 1525,
  [SMALL_STATE(91)] = 1535,
  [SMALL_STATE(92)] = 1543,
  [SMALL_STATE(93)] = 1551,
  [SMALL_STATE(94)] = 1561,
  [SMALL_STATE(95)] = 1571,
  [SMALL_STATE(96)] = 1581,
  [SMALL_STATE(97)] = 1591,
  [SMALL_STATE(98)] = 1601,
  [SMALL_STATE(99)] = 1611,
  [SMALL_STATE(100)] = 1621,
  [SMALL_STATE(101)] = 1628,
  [SMALL_STATE(102)] = 1635,
  [SMALL_STATE(103)] = 1642,
  [SMALL_STATE(104)] = 1649,
  [SMALL_STATE(105)] = 1656,
  [SMALL_STATE(106)] = 1663,
  [SMALL_STATE(107)] = 1670,
  [SMALL_STATE(108)] = 1677,
  [SMALL_STATE(109)] = 1684,
  [SMALL_STATE(110)] = 1691,
  [SMALL_STATE(111)] = 1698,
  [SMALL_STATE(112)] = 1705,
  [SMALL_STATE(113)] = 1712,
  [SMALL_STATE(114)] = 1719,
  [SMALL_STATE(115)] = 1726,
  [SMALL_STATE(116)] = 1733,
  [SMALL_STATE(117)] = 1740,
  [SMALL_STATE(118)] = 1747,
  [SMALL_STATE(119)] = 1754,
  [SMALL_STATE(120)] = 1761,
  [SMALL_STATE(121)] = 1768,
  [SMALL_STATE(122)] = 1775,
  [SMALL_STATE(123)] = 1782,
  [SMALL_STATE(124)] = 1789,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(117),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(124),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_def, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_goal_def_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goal_def_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goal_def_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goal_def_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_def, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_stmt, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_group, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_desc, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_cond, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_done, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_cond, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_list, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_block, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_decl, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_block, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_block, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_block, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_def, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_def, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 5, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_def, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_def, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_block, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_block, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_block, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_block, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_list, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 4, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_stmt, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_stmt, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_name, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_name, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_desc, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_desc, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_visited, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_visited, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit_stmt, 4, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exit_stmt, 4, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_desc, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_desc, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_stmt, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_stmt, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_portable, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_portable, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_stmt, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_npc_stmt, 1, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_name, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_name, 2, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_name, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_npc_name, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_desc, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_npc_desc, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_location, 3, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_npc_location, 3, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [309] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_trigger_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trigger_repeat1, 2, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_spinner_block_repeat1, 2, 0, 0),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_spinner_block_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [329] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_list_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_list_repeat1, 2, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wedge_stmt, 2, 0, 0),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [356] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__trigger_stmt, 2, 0, 0),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trigger_stmt, 2, 0, 0),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wedge_stmt, 4, 0, 0),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [372] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [376] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [380] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [382] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [384] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [388] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [390] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [394] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [396] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [400] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [402] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [404] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [406] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [408] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [410] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [414] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_amble_dsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "amble_dsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
